### ISSUE TITLE
please add instructions on how to run the server

### ISSUE THREAD

**Issue by egonw** [abmiguez/dummyServer#4]
Compiling is straightforward with the `pom.xml` but can you please add instructions on how to run the server?

**Comment by abmiguez** [comment]
Dear egown,
You can find instructions on how to run the server in the README of the repository:

_

> Clone the repository and make a JAR (select the main class Server) or simply download the most recent release. Then, open a terminal and execute the following command to start the Server:
> 
> java [-Xmx2G] [-Xms256M] -server -jar dummyserver.jar
> 
> Note that, the parameters between brackets are optional. However, it may be interesting to modify the maximum memory allocation and the initial memory allocation pool when starting the JVM (-Xmx and -Xms, respectively).
> 
> Once the Annotation Server is running, it will be possible to make requests! If you clone the code and open it in a IDE, you will see a JUnit test to make this requests automatically. To do this, you must execute the Server class first.

_

Best,
Aitor
